spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    user:
      name: admin
      password: admin

  freemarker:
    content-type: text/html